### ISSUE TITLE
how to get list_id value from json using mapper ?

### ISSUE THREAD

**Issue by jigs777** [javalnanda/AlamofireObjectMapperSample#1]
i want to get time_format , list_id  key value

**Comment by javalnanda** [comment]
From where? without looking at your JSON structure I cannot help you.

**Comment by jigs777** [comment]
{
	"err": 0,
	"result": [{
		"id": 71930,
		"account_id": 40869,
		"status": "enabled",
		"settings_data": {
			"time_format": "12h",
			"timezone": "US/Pacific",
			"fingerprint_versions": {
				"browser.browser-js": 1
			},
			"integrations": {
				"jira": {},
				"datadog": {},
				"bitbucket": {},
				"github": {},
				"trello": {
					"board_id": "xxx",
					"enabled": true,
					"access_token_user_id": 1234,
					"list_id": "xxxxx"
				},
				"slack": {
					"channel_id": "xxxx",
					"enabled": true,
					"access_token_user_id": "xx"
				},
				"webhook": {},
				"victorops": {},
				"asana": {},
				"pivotal": {},
				"campfire": {},
				"sprintly": {},
				"pagerduty": {},
				"hipchat": {},
				"email": {
					"enabled": true
				},
				"flowdock": {}
			}
		},
		"date_created": 1468068105,
		"date_modified": 1493409629,
		"name": "Android_ParentApp"
	}, {
		"id": 71931,
		"account_id": 40869,
		"status": "enabled",
		"settings_data": {
			"time_format": "12h",
			"timezone": "US/Pacific",
			"fingerprint_versions": {
				"browser.browser-js": 1
			},
			"integrations": {
				"jira": {},
				"datadog": {},
				"bitbucket": {},
				"github": {},
				"trello": {
					"board_id": "xxxx",
					"enabled": true,
					"access_token_user_id": 1234,
					"list_id": "xxxxx"
				},
				"slack": {
					"channel_id": "xxxxx",
					"enabled": true,
					"access_token_user_id": "xxx"
				},
				"webhook": {},
				"victorops": {},
				"asana": {},
				"pivotal": {},
				"campfire": {},
				"sprintly": {},
				"pagerduty": {},
				"hipchat": {},
				"email": {
					"enabled": true
				},
				"flowdock": {}
			}
		},
		"date_created": 1468068142,
		"date_modified": 1493409658,
		"name": "Android_TeacherApp"
	}]
}

**Comment by jigs777** [comment]
This is json

**Comment by javalnanda** [comment]
Ok from the sample itself. I thought you are trying out different JSON.

There are 2 ways to achieve it:
1) If you want just single value from nested JSON then access it via dot notation.
`listId <- map["settings_data.integrations.trello.list_id"]`

2) Create model objects for nested JSON:

```
class SettingsData:NSObject, Mappable {
    var integrations: Integrations?

    override init() {
        super.init()
    }

    convenience required init?(map: Map) {
        self.init()
    }

    func mapping(map: Map) {
        integrations <- map["integrations"]
    }
}

class Trello: NSObject, Mappable {
    var listId: String?

    override init() {
        super.init()
    }

    convenience required init?(map: Map) {
        self.init()
    }

    func mapping(map: Map) {
        listId <- map["list_id"]
    }
}

class Integrations: NSObject, Mappable {
    var trello: Trello?

    override init() {
        super.init()
    }

    convenience required init?(map: Map) {
        self.init()
    }

    func mapping(map: Map) {
        trello <- map["trello"]
    }
}
class Project: NSObject, Mappable {

	var projectId: Int?
    var accountId: Int?
	var dateCreated: Int?
	var dateModified: Int?
	var name: String?
	var status: String?
	var listId: String?
    var settingsData: SettingsData?
    override init() {
        super.init()
    }

    convenience required init?(map: Map) {
        self.init()
    }

    func mapping(map: Map) {
        projectId <- map["id"]
        accountId <- map["account_id"]
        dateCreated <- map["date_created"]
        dateModified <- map["date_modified"]
        name <- map["name"]
        status <- map["status"]
        listId <- map["settings_data.integrations.trello.list_id"]
        settingsData <- map["settings_data"]
    }

}

```
